# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-17 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cookie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='date',
            new_name='timestamp',
        ),
    ]
